### ISSUE TITLE
Cannot change the small octicon's color on the homepage 

### ISSUE THREAD

**Issue by MFYDev** [TylerByte666/gitea-templates#1]
Hi there,

First thank you for opening source about this excellent customize template.

When I use it, it all works well except the link colors and octicon colors on the homepage. They all display as green not red or any other colors.

And I found that it is .home .hero .octicon{} in the css which has the color definition of them. So I changed the theme-red.css by adding a line which is .home .hero .octicon{ color:#ffffff} and restart the gitea. Then nothing changed. It really makes me confuse why this happened.

Would you please give me some help? Or you can change it directly in the theme-red.css?

It will be so much appreciated if you could tell me how to do that.

Thank you again for this brilliant work!

**Comment by MFYDev** [comment]
![wrongcolor](https://user-images.githubusercontent.com/53750381/71568575-5ccc2380-2b03-11ea-91da-a202f26609dd.PNG)

The picture can display what I said more clearly.

**Comment by MFYDev** [comment]
I tried to add "main-red" to every line of the icon definitions in the home.tmpl
Such as 
```
<div class="eight wide center column">
				<h1 class="hero ui icon header">
					<i class="octicon octicon-code main-red"></i> 开源化
				</h1>
```
But still noting happened. Really weird.

**Comment by TylerByte666** [comment]
Hi, thanks for using my Templates :) let me have a look and I will be in
touch :)

**Comment by MFYDev** [comment]
Hi Tyler,
Thank you for replying to me so quickly.
After searching for this problem for about 4 hours. I found that the "theme-red.css" will be saved in gitea, I can import this file even though I have deleted it. What I am trying to do is  I just renamed it to another name and restart the gitea again and again. Only in this way can I customize on your theme.

That is really drives me crazy cause I need to do this step by step. Because I really do not such good at front end. I have to change a little bit and restart the gitea. Could you please add another green theme? Cause from my perspective I prefer code in black and green. You can have a look on what I am doing at https://gitea.fanyangmeng.com . I am still in process to customize your theme. Really exausted. If you can make a green one I will definitely be a sponser to you.

Thank you in advance!

**Comment by TylerByte666** [comment]
I also prefer the green and black. 

My company needed the red as the main colors. I will work on a green one starting in January, I will link the new template files here when complete and let you know :)

I also think that the green fits the theme better, so I will call it gitea-templates-matrix for green and gitea-templates-hell for the red. 😄

**Comment by MFYDev** [comment]
HAHA that sound so nice!
Seems we like the same my friend! Matrix is so much cooler!
Thank you so much for your fast response to me! And I am really looking forward the Matrix templates.
Before you release that I will keep customizing it as much as I can to green cause I really like this theme so much and cannot wait to use it.
Thank you for your excellent job again!

**Comment by MFYDev** [comment]
Hi there, just wanna let you know that in the latest version of Gitea, it has some changes in the template and now all your template becomes unfitable to Gitea.

Please notice these changes when you creat the template

**Comment by MFYDev** [comment]
Hi there, have you received that? Please note this in case you have to change a lot after all things done. 
: )

**Comment by MFYDev** [comment]
I try for serveral times and I thought the main problem is in the head.tmpl and theme-red.css
Maybe something changes in these two files.

**Comment by TylerByte666** [comment]
hi, i am aware :) will be done before the end of jan :)

**Comment by MFYDev** [comment]
emmmm, it is already the last day of Jan mate.
No rush, just wanna ask that if you have made any progress? 
Really appreciate any reply and response

**Comment by TylerByte666** [comment]
New files:
https://github.com/TylerByte666/gitea-matrix-template.

Almost done. Just need to push the rest tonight.
